// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddAudioFile(arg1) {
  return window['go']['main']['App']['AddAudioFile'](arg1);
}

export function GetCaptureDeviceID() {
  return window['go']['main']['App']['GetCaptureDeviceID']();
}

export function GetPlaybackDeviceID() {
  return window['go']['main']['App']['GetPlaybackDeviceID']();
}

export function ListAudioFileKeybindings() {
  return window['go']['main']['App']['ListAudioFileKeybindings']();
}

export function ListAudioFiles() {
  return window['go']['main']['App']['ListAudioFiles']();
}

export function ListCaptureDevices() {
  return window['go']['main']['App']['ListCaptureDevices']();
}

export function ListPlaybackDevices() {
  return window['go']['main']['App']['ListPlaybackDevices']();
}

export function LoopbackAudio(arg1) {
  return window['go']['main']['App']['LoopbackAudio'](arg1);
}

export function OpenMultipleFilesDialog(arg1) {
  return window['go']['main']['App']['OpenMultipleFilesDialog'](arg1);
}

export function PlayAudioFile(arg1) {
  return window['go']['main']['App']['PlayAudioFile'](arg1);
}

export function RemoveAudioFile(arg1) {
  return window['go']['main']['App']['RemoveAudioFile'](arg1);
}

export function RemoveAudioFileKeybinding(arg1) {
  return window['go']['main']['App']['RemoveAudioFileKeybinding'](arg1);
}

export function SetAudioFileKeybinding(arg1, arg2) {
  return window['go']['main']['App']['SetAudioFileKeybinding'](arg1, arg2);
}

export function SetCaptureDeviceID(arg1) {
  return window['go']['main']['App']['SetCaptureDeviceID'](arg1);
}

export function SetPlaybackDeviceID(arg1) {
  return window['go']['main']['App']['SetPlaybackDeviceID'](arg1);
}

export function StopAudioFile(arg1) {
  return window['go']['main']['App']['StopAudioFile'](arg1);
}
