// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCaptureDeviceID() {
  return window['go']['main']['App']['GetCaptureDeviceID']();
}

export function GetPlaybackDeviceID() {
  return window['go']['main']['App']['GetPlaybackDeviceID']();
}

export function ListCaptureDevices() {
  return window['go']['main']['App']['ListCaptureDevices']();
}

export function ListPlaybackDevices() {
  return window['go']['main']['App']['ListPlaybackDevices']();
}

export function SetCaptureDeviceID(arg1) {
  return window['go']['main']['App']['SetCaptureDeviceID'](arg1);
}

export function SetPlaybackDeviceID(arg1) {
  return window['go']['main']['App']['SetPlaybackDeviceID'](arg1);
}
