// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetCaptureDeviceID():Promise<string>;

export function GetPlaybackDeviceID():Promise<string>;

export function ListCaptureDevices():Promise<Array<main.MediaDeviceInfo>>;

export function ListPlaybackDevices():Promise<Array<main.MediaDeviceInfo>>;

export function SetCaptureDeviceID(arg1:string):Promise<void>;

export function SetPlaybackDeviceID(arg1:string):Promise<void>;
