// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {context} from '../models';

export function AddAudioFile(arg1:string):Promise<void>;

export function GetCaptureDeviceID():Promise<string>;

export function GetPlaybackDeviceID():Promise<string>;

export function ListAudioFileKeybindings():Promise<{[key: string]: string}>;

export function ListAudioFiles():Promise<Array<string>>;

export function ListCaptureDevices():Promise<Array<main.MediaDeviceInfo>>;

export function ListPlaybackDevices():Promise<Array<main.MediaDeviceInfo>>;

export function LoopbackAudio(arg1:context.Context):Promise<void>;

export function OpenMultipleFilesDialog(arg1:main.OpenDialogOptions):Promise<Array<string>>;

export function PlayAudioFile(arg1:string):Promise<void>;

export function RemoveAudioFile(arg1:string):Promise<void>;

export function RemoveAudioFileKeybinding(arg1:string):Promise<void>;

export function SetAudioFileKeybinding(arg1:string,arg2:string):Promise<void>;

export function SetCaptureDeviceID(arg1:string):Promise<void>;

export function SetPlaybackDeviceID(arg1:string):Promise<void>;

export function StopAudioFile(arg1:string):Promise<void>;
